arch: arm: fix undefined symbol error for armclang
arch_irq_enable(), arch_irq_disable(), arch_irq_is_enabled() are
exported to assembly via GTEXT() but are implemented as C macro mappings
in some configurations. This can leave undefined symbol in objects that
include irq.h, which some linkers diagnose as errors as seen below with
armlink:
```
Error: L6218E: Undefined symbol arch_irq_enable (referred from reset.o).
Error: L6218E: Undefined symbol arch_irq_disable (referred from
reset.o).
Error: L6218E: Undefined symbol arch_irq_is_enabled (referred from
reset.o).
```
Map the arch_irq_* to appropriate underlying implementation in the
_ASMLANGUAGE path so that all assembly-visible exports resolve to real
symbols.

Signed-off-by: Sudan Landge <sudan.landge@arm.com>