scripts: ci: guideline_check: ignore tests/posix/ in coccinelle
Exclulde `tests/posix/` when running coccinelle checks for reserved names
since POSIX implements much of the reserved names.

This avoids the following failure in CI

```shell
Error: tests/posix/xsi_single_process/src/putenv.c:12: WARNING: \
  Violation to rule 21.2 (Should not used a reserved identifier) - putenv
```

Signed-off-by: Chris Friedt <chris@fr4.co>